import re
import sys

# ---- Lexer ----
KEYWORDS = {'rule', 'if', 'then', 'AND'}
_TOK = re.compile(r'\s+|(AND|[a-z][a-z0-9_]*)|(\d+)|([:><=])')

def tokenize(src):
    tokens, i = [], 0
    while i < len(src):
        m = _TOK.match(src, i)
        if not m:
            raise SyntaxError(f"Unexpected character {src[i]!r} at position {i}")
        i = m.end()
        if m.group(1):
            w = m.group(1)
            tokens.append((w if w in KEYWORDS else 'id', w))
        elif m.group(2):
            tokens.append(('value', int(m.group(2))))
        elif m.group(3):
            tokens.append((m.group(3), m.group(3)))
    tokens.append(('$', '$'))
    return tokens

# ---- Parser (LL(1) recursive descent) ----
class _P:
    def __init__(self, t):
        self.t = t
        self.i = 0
    def peek(self):
        return self.t[self.i]
    def eat(self, k):
        if self.peek()[0] != k:
            raise SyntaxError(f"Expected {k}, got {self.peek()}")
        v = self.t[self.i]
        self.i += 1
        return v
    def program(self):
        rs = []
        while self.peek()[0] == 'rule':
            rs.append(self.rule())
        if self.peek()[0] != '$':
            raise SyntaxError(f"Unexpected token {self.peek()}")
        return ('Program', rs)
    def rule(self):
        self.eat('rule')
        n = self.eat('id')[1]
        self.eat(':')
        self.eat('if')
        c = self.cond()
        self.eat('then')
        a = self.eat('id')[1]
        return ('Rule', n, c, ('Action', a))
    def cond(self):
        l = self.atom()
        while self.peek()[0] == 'AND':
            self.eat('AND')
            l = ('And', l, self.atom())
        return l
    def atom(self):
        n = self.eat('id')[1]
        if self.peek()[0] in ('>', '<', '='):
            op = self.eat(self.peek()[0])[0]
            v = self.eat('value')[1]
            return ('Cmp', n, op, v)
        return ('Fact', n)

def parse(src):
    return _P(tokenize(src)).program()

# ---- Interpreter (fixed-point evaluation) ----
def eval_cond(c, vs, fs):
    t = c[0]
    if t == 'And':
        return eval_cond(c[1], vs, fs) and eval_cond(c[2], vs, fs)
    if t == 'Cmp':
        _, x, op, v = c
        if x not in vs:
            return False
        xv = vs[x]
        return (op == '>' and xv > v) or (op == '<' and xv < v) or (op == '=' and xv == v)
    return c[1] in fs

def execute(program, vs, init_facts):
    active = set(init_facts)
    derived = set()
    changed = True
    while changed:
        changed = False
        for r in program[1]:
            if eval_cond(r[2], vs, active):
                a = r[3][1]
                if a not in active:
                    active.add(a)
                    derived.add(a)
                    changed = True
    return derived

# ---- Static analyzer ----
def _facts(c):
    if c[0] == 'And':
        return _facts(c[1]) | _facts(c[2])
    if c[0] == 'Fact':
        return {c[1]}
    return set()

def _can_make_true(c, vs, init_facts, actions):
    t = c[0]
    if t == 'And':
        return _can_make_true(c[1], vs, init_facts, actions) and _can_make_true(c[2], vs, init_facts, actions)
    if t == 'Cmp':
        _, x, op, v = c
        if x not in vs:
            return False
        xv = vs[x]
        return (op == '>' and xv > v) or (op == '<' and xv < v) or (op == '=' and xv == v)
    return c[1] in init_facts or c[1] in actions

def analyze(program, vs, init_facts):
    rules = program[1]
    msgs = []
    if not rules:
        return msgs
    by_action = {}
    for r in rules:
        by_action.setdefault(r[3][1], []).append(r)
    flagged = set()
    for a, grp in by_action.items():
        if len(grp) < 2:
            continue
        conds = [r[2] for r in grp]
        names = [r[1] for r in grp]
        if all(c == conds[0] for c in conds):
            msgs.append(f"Redundant rules: {', '.join(names)}")
        else:
            msgs.append(f"Action {a} generated by {', '.join(names)}")
        flagged.update(names)
    if len(rules) >= 2:
        actions = {r[3][1] for r in rules}
        consumed = set()
        for r in rules:
            consumed |= _facts(r[2])
        for r in rules:
            if r[1] in flagged or r[3][1] in consumed:
                continue
            if _can_make_true(r[2], vs, init_facts, actions):
                continue
            msgs.append(f"Potentially inactive rule: {r[1]}")
    return msgs

# ---- Entry point ----
src = sys.stdin.read()
if 'State:' in src:
    rules_src, state_src = src.split('State:', 1)
else:
    rules_src, state_src = src, ''

vs, init_facts = {}, set()
for line in state_src.splitlines():
    s = line.strip()
    if not s:
        continue
    if '=' in s:
        x, v = s.split('=')
        vs[x.strip()] = int(v.strip())
    else:
        init_facts.add(s)

program = parse(rules_src)
derived = execute(program, vs, init_facts)

if derived:
    for f in sorted(derived):
        print(f)
else:
    print('(no output)')

for m in analyze(program, vs, init_facts):
    print(m)
